### ISSUE TITLE
Cyclic reboot (transferred from https://github.com/Ninoh-FOX/RG280V_ROGUE/issues/3)

### ISSUE THREAD

**Issue by bigfatbrowncat** [Ninoh-FOX/toolchain#5]
Hi! I've managed to build the sd_image from your repo and flashed it into my RG280V SD-card.

The console starts to boot, shows the graphical logo, reports that it is creating a swap (but I don't see any progress bar change there), shows that it "wipes the old config" and reboots. Then the same repeats over and over.

How to debug this? What could be the problem?

I was building in Ubuntu 18.04, had to make some small patches in the build scripts, but I haven't changed any C/C++ code and haven't changed anything major.

**Comment by bigfatbrowncat** [comment]
You've said that it could be a data partition problem.

But why it occured? I was running all the scripts from their folders (because some of them were not running succesfully from the root folder of the repo). Maybe that was the cause? How they should be run?

**Comment by Ninoh-FOX** [comment]
Do you make the sdimage with sudo command?

**Comment by bigfatbrowncat** [comment]
Interesting question. I did not first, but then it requesed root access and I entered the password...

**Comment by bigfatbrowncat** [comment]
I'm going to rebuild everything from scratch. And this time run it from SUDO.
What about the directories? I was doing cd into each script's directory. Was it right?

May there be any other possible causes of the problem?

**Comment by bigfatbrowncat** [comment]
I have done it correct this time. Unfortunately, it didn't help.
Here is the tail of my log:
[sd_image.log](https://github.com/Ninoh-FOX/toolchain/files/6064818/sd_image.log)

**Comment by Ninoh-FOX** [comment]
Hmmm I don't see nothing strange in the log, how you has a diferent linux system... Do you make the rebuild script, for make /opt/gcw0_toolchain for your system?

**Comment by bigfatbrowncat** [comment]
I was rebuilding everything from scratch on Ubuntu 18.04.3
Unfortunately, I had to update some components cause of build errors, because of the newer, incompatible Perl version.
I believe that my updates could lead to some incompatibilities, but I don't know how to diagnose the build

When the device runs, before it reboots it shows some error for a fraction of second, but I don't have time to read it... Is it possible to extract some logs from the SD afterwards? Do you know any method?

**Comment by bigfatbrowncat** [comment]
I have changed 

    make rg350_defconfig

to

    make rg280v_defconfig

in the rebuild.sh. Shouldn't I have?

**Comment by bigfatbrowncat** [comment]
I have reverted avahi to the old version and now it works fine. The new ones (0.8 and 0.7) were the troublemakers.
