### ISSUE TITLE
/opt/gcw0-toolchain/usr/bin/automake is written for old Perl

### ISSUE THREAD

**Issue by geniot** [Ninoh-FOX/toolchain#7]
As I'm trying to automake from Fuse emulator's Makefile.am I'm getting 

$ automake --add-missing --copy --force-missing

Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /opt/gcw0-toolchain/usr/bin/automake line 3930.

The fix (backslashing brackets):
3930
`
  #$text =~ s/\${([^ \t=:+{}]+)}/substitute_ac_subst_variables_worker ($1)/ge;
`
`
  $text =~ s/\$\{([^ \t=:+{}]+)\}/substitute_ac_subst_variables_worker ($1)/ge;
`

It seems to be related to Perl version. I'm using:
This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

**Comment by Ninoh-FOX** [comment]
fixed
