### ISSUE TITLE
CMake cannot find SDL2

### ISSUE THREAD

**Issue by geniot** [Ninoh-FOX/toolchain#8]
CMake in  /opt/gcw0-toolchain/usr/bin/cmake uses  /opt/gcw0-toolchain/usr/share/cmake-3.1/Modules/ 
There is FindSDL.cmake and other FindSDL_* but no FindSDL2. Developers add custom FindSDL_ to their source code. Eg. here:
https://github.com/brendan-w/collector/tree/master/cmake
But even the existing FindSDL.cmake cannot find SDL in 
/opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib
Why? Can it use a relative path? I'm not sure yet.

To fix this in my case, FIND_LIBRARY needs to be updated. Eg. 

FIND_LIBRARY(SDL2_LIBRARY_TEMP
  NAMES SDL2
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib
  PATHS
  /sw
  /opt/local
  /opt/csw
  /opt
  /opt/gcw0-toolchain/usr/mipsel-gcw0-linux-uclibc/sysroot/usr/lib
)

There is a way to use $ENV{SDL2DIR} but I still need to learn how.

**Comment by Ninoh-FOX** [comment]
I think that the problem was that the old codo was erase from github, I am rewrite the package.
