### ISSUE TITLE
Missing libfl.so.2 while building ScummVM

### ISSUE THREAD

**Issue by fenuks** [Ninoh-FOX/toolchain#9]
I'm trying to build OPK for the latest ScummVM. I have downloaded the latest Debian toolchain from the releases page, extracted it into /opt/gcw0-toolchain, and executed `bash backends/platform/dingux/build.gcw0.sh` from ScummVM root directory. It builds for a while, until it tries to link:

```
    C++      engines/xeen/xsurface.o
    AR       engines/libengines.a
mipsel-linux-ar: error while loading shared libraries: libfl.so.2: cannot open shared object file: No such file or directory
```
libfl.so.2 is shared library provided by flex. Toolchain contains flex, could it be shipped with this shared library as well?

**Comment by Ninoh-FOX** [comment]
Do you tried install libfl-dev package from terminal in your linux system?

**Comment by fenuks** [comment]
Thank you, that fixed the issue. I thought build log was referring to target lib, but instead it wanted host one that I didn't have installed… After installing it, I was able to finish compilation. Thank you, again.
